### ISSUE TITLE
HM3D Bounding box of the annotations

### ISSUE THREAD

**Issue by DevXiaoYan** [fmolivato/almost-vio#1]
https://github.com/matterport/habitat-matterport-3dresearch/issues/32#issuecomment-2330195639
Hello, I saw that you have solved object segmentation in HM3D. Can you share your approach and code? Thank you for the compensation.

**Comment by fmolivato** [comment]
Hi,
unfortunately I can't release the code just yet (see https://github.com/matterport/habitat-matterport-3dresearch/issues/32#issuecomment-2331053831)

This repository is not about HM3D but visual odometry on the ADVIO dataset thus I close this issue.
For further infos lets talk on the matterport repo you quoted.
